---
- name: Get user home directory.
  ansible.builtin.getent:
    database: passwd
    split: ':'
    key: '{{ item.user }}'

- name: Init chezmoi.
  become: true
  become_user: '{{ item.user }}'
  ansible.builtin.command:
    cmd: /usr/local/bin/chezmoi init --apply {{ item.repo | default('') }}
    creates: "{{ getent_passwd[item.user][4] }}/.local/share/chezmoi"

- name: Set helper variable
  ansible.builtin.set_fact:
    enable_service: '{{ item.start_timer is defined and (item.start_timer | bool) }}'

- name: Configure update systemd timer.
  ansible.builtin.systemd:
    name: chezmoi-update@{{ item.user }}.timer
    state: '{{ enable_service | ternary("started", "stopped") }}'
    enabled: '{{ enable_service }}'
