---
# Get latest version
- name: Get the latest version
  when: (chezmoi_version is not defined) or (chezmoi_version == 'latest')
  run_once: true
  block:
  - name: Determine latest GitHub release (local).
    delegate_to: localhost
    become: false
    ansible.builtin.uri:
      url: https://api.github.com/repos/{{ chezmoi_repo }}/releases/latest
      body_format: json
    register: _github_release
    until: _github_release.status == 200
    retries: 5

  - name: Set chezmoi_version.
    ansible.builtin.set_fact:
      chezmoi_version: "{{ _github_release.json.tag_name | regex_replace('^v?(.*)$', '\\1') }}"
      chezmoi_tag: "{{ _github_release.json.tag_name }}"

- name: Test if chezmoi is already installed.
  ansible.builtin.stat:
    path: /usr/local/bin/chezmoi
  register: cz

- name: Get installed version.
  ansible.builtin.command:
    cmd: /usr/local/bin/chezmoi --version
  changed_when: false
  register: cz_ver
  when: cz.stat.executable is defined and cz.stat.executable

- name: Parse version string.
  ansible.builtin.set_fact:
    chezmoi_installed_tag: "{{ cz_ver.stdout | regex_search('chezmoi version ([^,]+)', '\\1') | first }}"
  when: cz_ver.rc is defined and cz_ver.rc == 0

- name: Download chezmoi.
  ansible.builtin.unarchive:
    src: https://github.com/{{ chezmoi_repo }}/releases/download/v{{ chezmoi_version }}/chezmoi_{{ chezmoi_version }}_linux_{{ go_arch }}.tar.gz
    dest: /usr/local/bin
    include:
    - chezmoi
    remote_src: true
    owner: root
    group: root
    mode: '0755'
  when: chezmoi_installed_tag is not defined or chezmoi_installed_tag != chezmoi_tag

- name: Add update systemd service.
  ansible.builtin.copy:
    src: chezmoi-update@.service
    dest: /etc/systemd/system/chezmoi-update@.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload daemons

- name: Add update systemd timer.
  ansible.builtin.template:
    src: chezmoi-update@.timer.j2
    dest: /etc/systemd/system/chezmoi-update@.timer
    owner: root
    group: root
    mode: '0644'
  notify: Reload daemons

- name: Initialize chezmoi for users.
  ansible.builtin.include_tasks: init.yml
  loop: '{{ chezmoi_users }}'
