---
- name: Converge
  hosts: all
  vars:
    chezmoi_users:
      - user: testuser
        repo: https://gitea.panfiloslab.com/ansible/dotfiles-server.git
        update: true
  pre_tasks:
    - name: Ensure test user exists.
      ansible.builtin.user:
        name: '{{ chezmoi_users[0].user }}'
        state: present
  tasks:
    - name: Include ansible-role-chezmoi
      include_role:
        name: ansible-role-chezmoi
