---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure test user exists.
      ansible.builtin.user:
        name: '{{ chezmoi_users[0].user }}'
        state: present
  tasks:
    - name: Include ansible-role-chezmoi
      include_role:
        name: ansible-role-chezmoi
