---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: bookworm
    image: ghcr.io/alecunsolo/bookworm-base-systemd:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
  - name: bullseye
    image: ghcr.io/alecunsolo/bullseye-base-systemd:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
  - name: ubuntu2204
    image: ghcr.io/alecunsolo/ubuntu2204-base-systemd:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        chezmoi_users:
          - user: testuser
            repo: alecunsolo/dotfiles-server
            start_timer: true
verifier:
  name: ansible
