---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        chezmoi_users:
          - user: testuser
            repo: https://gitea.panfiloslab.com/ansible/dotfiles-server.git
            start_timer: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
