---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rhel
    image: docker.io/almalinux/9-init:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: /usr/sbin/init
  - name: debian
    image: ghcr.io/alecunsolo/debian-base-systemd:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
  - name: ubuntu
    image: ghcr.io/alecunsolo/ubuntu-base-systemd:latest
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        chezmoi_users:
          - user: testuser
            repo: alecunsolo/dotfiles-server
            start_timer: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
