---
- name: Verify
  hosts: all
  become: true
  vars:
    chezmoi_init_repo_dir: .local/share/chezmoi
  tasks:
  - name: Get stat of test user chezmoi directory
    ansible.builtin.stat:
      path: /home/{{ chezmoi_users[0].user }}/{{ chezmoi_init_repo_dir }}
    register: cz_init
  - name: Test variables
    ansible.builtin.assert:
      that:
      - cz_init.stat.exists
      fail_msg: Chezmoi was not initialized
